import { notFound } from "next/navigation";
import { ActivityList } from "@/components/activity-list";
import { EnvelopeDetailActions } from "@/components/envelope-detail-actions";
import { EnvelopeIcon } from "@/components/icon";
import { requireCurrentUser } from "@/lib/auth";
import { getBudgetSummary } from "@/lib/services/budget-service";
import { findEnvelope } from "@/lib/services/envelope-service";
import { listTransactions } from "@/lib/services/transaction-service";
import { formatMoney } from "@/lib/utils";
export default async function EnvelopeDetailPage({params}:{params:Promise<{id:string}>}){const user=await requireCurrentUser();const{id}=await params;let envelope;try{envelope=await findEnvelope(user.id,id)}catch{return notFound()}const budget=await getBudgetSummary(user.id,envelope.budgetMonthId);const detail=budget.envelopes.find(item=>item.id===id)!;const rows=await listTransactions(user.id,{envelopeId:id,limit:100});const actual=detail.type==="savings"?detail.saved:detail.spent;return <div className="page"><section className={`detail-hero ${detail.accent}`}><span className="detail-icon"><EnvelopeIcon name={detail.icon} size={28}/></span><span className="eyebrow">{detail.type==="savings"?"Savings envelope":"Spending envelope"}</span><h1>{detail.name}</h1><strong>{formatMoney(detail.remaining)}</strong><p>remaining from {formatMoney(detail.allocatedAmount)}</p><div className="progress"><span style={{width:`${Math.min(detail.used,100)}%`}}/></div><div className="detail-stats"><div><span>{detail.type==="savings"?"Saved":"Spent"}</span><strong>{formatMoney(actual)}</strong></div><div><span>Used</span><strong>{detail.used}%</strong></div><div><span>Status</span><strong>{detail.label}</strong></div></div></section><EnvelopeDetailActions envelope={detail} budget={budget}/><section><div className="section-heading"><div><span className="eyebrow">History</span><h2>Envelope activity</h2></div></div><ActivityList rows={rows.items} envelopes={budget.envelopes.map(item=>({id:item.id,name:item.name}))}/></section></div>}
