"use client";
import { ArrowDownLeft, Check, ChevronDown, Pencil, Search, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { apiRequest } from "@/lib/api-client";
import { formatMoney } from "@/lib/utils";
import { ConfirmDialog } from "./confirm-dialog";
import { Dialog } from "./dialog";
import { EnvelopeIcon } from "./icon";

type Row = { id: string; title: string; amount: string; transactionDate: Date | string; merchant: string | null; note: string | null; type: "expense" | "saving"; envelopeId: string; envelopeName: string; envelopeIcon: string; envelopeAccent: string; budgetMonthId: string; };
type EnvelopeOption = { id: string; name: string };
export function ActivityList({ rows, envelopes = [], compact = false }: { rows: Row[]; envelopes?: EnvelopeOption[]; compact?: boolean }) {
  const [search,setSearch]=useState(""); const [filter,setFilter]=useState(""); const [sort,setSort]=useState("newest"); const [editing,setEditing]=useState<Row|null>(null); const [deleting,setDeleting]=useState<Row|null>(null); const [pending,setPending]=useState(false); const router=useRouter();
  const visible=useMemo(()=>rows.filter(row=>(!search||`${row.title} ${row.merchant??""}`.toLowerCase().includes(search.toLowerCase()))&&(!filter||row.envelopeId===filter)).sort((a,b)=>sort==="highest"?Number(b.amount)-Number(a.amount):sort==="lowest"?Number(a.amount)-Number(b.amount):sort==="oldest"?+new Date(a.transactionDate)-+new Date(b.transactionDate):+new Date(b.transactionDate)-+new Date(a.transactionDate)),[rows,search,filter,sort]);
  async function remove(){if(!deleting)return;setPending(true);try{await apiRequest(`/api/v1/transactions/${deleting.id}`,{method:"DELETE"});toast.success("Transaction deleted");setDeleting(null);router.refresh()}catch(error){toast.error(error instanceof Error?error.message:"Could not delete transaction")}finally{setPending(false)}}
  async function update(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;setPending(true);const data=new FormData(event.currentTarget);try{await apiRequest(`/api/v1/transactions/${editing.id}`,{method:"PATCH",body:JSON.stringify({title:data.get("title"),amount:data.get("amount"),transactionDate:new Date(String(data.get("date"))).toISOString(),merchant:data.get("merchant")||null,note:data.get("note")||null,...(data.get("envelopeId")?{envelopeId:data.get("envelopeId"),budgetMonthId:editing.budgetMonthId}:{})})});toast.success("Expense updated");setEditing(null);router.refresh()}catch(error){toast.error(error instanceof Error?error.message:"Could not update expense")}finally{setPending(false)}}
  return <>
    {!compact&&<><div className="filters"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search descriptions or merchants" aria-label="Search activity"/></label><label className="select-control"><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter by envelope"><option value="">All envelopes</option>{envelopes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><ChevronDown/></label><label className="select-control"><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort transactions"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="highest">Highest amount</option><option value="lowest">Lowest amount</option></select><ChevronDown/></label></div>{envelopes.length>0&&<div className="filter-chips" aria-label="Quick envelope filters"><button className={!filter?"active":""} onClick={()=>setFilter("")}>{!filter&&<Check/>}All</button>{envelopes.map(item=><button key={item.id} className={filter===item.id?"active":""} onClick={()=>setFilter(item.id)}>{filter===item.id&&<Check/>}{item.name}</button>)}</div>}</>}
    {visible.length?<div className={`activity-list ${compact?"compact-list":""}`}>{visible.map(row=><article className="transaction-row" key={row.id}><span className={`transaction-icon ${row.envelopeAccent}`}><EnvelopeIcon name={row.envelopeIcon}/></span><div className="transaction-copy"><strong>{row.title}</strong><span>{row.envelopeName} · {new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(new Date(row.transactionDate))}{row.merchant?` · ${row.merchant}`:""}</span></div><strong className={row.type==="saving"?"positive":""}>{row.type==="saving"?"+":"−"}{formatMoney(row.amount)}</strong><div className="row-actions"><button onClick={()=>setEditing(row)} aria-label={`Edit ${row.title}`}><Pencil/></button><button onClick={()=>setDeleting(row)} aria-label={`Delete ${row.title}`}><Trash2/></button></div></article>)}</div>:<div className="empty-state compact"><span><ArrowDownLeft/></span><h3>No spending yet</h3><p>Your budget is untouched. Add an expense when money moves.</p></div>}
    <Dialog open={Boolean(editing)} onClose={()=>setEditing(null)} title="Edit transaction" eyebrow={editing?.envelopeName}><form className="form-grid" onSubmit={update}><label><span>Description</span><input name="title" defaultValue={editing?.title} required maxLength={120}/></label><label><span>Amount</span><div className="money-input"><b>₹</b><input name="amount" defaultValue={editing?.amount} inputMode="decimal" pattern="\d+(\.\d{1,2})?" required/></div></label>{envelopes.length>0&&<label><span>Envelope</span><div className="select-control field-select"><select name="envelopeId" defaultValue={editing?.envelopeId}>{envelopes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><ChevronDown/></div></label>}<label><span>Date</span><input type="date" name="date" defaultValue={editing?new Date(editing.transactionDate).toISOString().slice(0,10):""} required/></label><label><span>Merchant <i>optional</i></span><input name="merchant" defaultValue={editing?.merchant??""} maxLength={120}/></label><label><span>Note <i>optional</i></span><textarea name="note" defaultValue={editing?.note??""} rows={2} maxLength={500}/></label><button className="primary-button" disabled={pending}>{pending?"Saving…":"Save transaction"}</button></form></Dialog>
    <ConfirmDialog open={Boolean(deleting)} onClose={()=>setDeleting(null)} onConfirm={remove} pending={pending} title="Delete this transaction?" description={deleting?`${deleting.title} for ${formatMoney(deleting.amount)} will be permanently removed and all monthly totals will recalculate.`:""} confirmLabel="Delete transaction"/>
  </>;
}
