"use client";
import { ArrowDownLeft, Pencil, Search, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { apiRequest } from "@/lib/api-client";
import { formatMoney } from "@/lib/utils";
import { Dialog } from "./dialog";
import { EnvelopeIcon } from "./icon";
type Row = { id: string; title: string; amount: string; transactionDate: Date | string; merchant: string | null; note: string | null; type: "expense" | "saving"; envelopeId: string; envelopeName: string; envelopeIcon: string; envelopeAccent: string; budgetMonthId: string; };
export function ActivityList({ rows, envelopes = [] }: { rows: Row[]; envelopes?: { id: string; name: string }[] }) {
  const [search,setSearch]=useState(""); const [filter,setFilter]=useState(""); const [sort,setSort]=useState("newest"); const [editing,setEditing]=useState<Row|null>(null); const [pending,setPending]=useState(false); const router=useRouter();
  const visible=useMemo(()=>rows.filter(row=>(!search||`${row.title} ${row.merchant??""}`.toLowerCase().includes(search.toLowerCase()))&&(!filter||row.envelopeId===filter)).sort((a,b)=>sort==="highest"?Number(b.amount)-Number(a.amount):sort==="lowest"?Number(a.amount)-Number(b.amount):sort==="oldest"?+new Date(a.transactionDate)-+new Date(b.transactionDate):+new Date(b.transactionDate)-+new Date(a.transactionDate)),[rows,search,filter,sort]);
  async function remove(id:string){if(!confirm("Delete this transaction? Your totals will be recalculated."))return;try{await apiRequest(`/api/v1/transactions/${id}`,{method:"DELETE"});toast.success("Transaction deleted");router.refresh()}catch(error){toast.error(error instanceof Error?error.message:"Could not delete transaction")}}
  async function update(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;setPending(true);const data=new FormData(event.currentTarget);try{await apiRequest(`/api/v1/transactions/${editing.id}`,{method:"PATCH",body:JSON.stringify({title:data.get("title"),amount:data.get("amount"),transactionDate:new Date(String(data.get("date"))).toISOString(),merchant:data.get("merchant")||null,note:data.get("note")||null})});toast.success("Expense updated");setEditing(null);router.refresh()}catch(error){toast.error(error instanceof Error?error.message:"Could not update expense")}finally{setPending(false)}}
  return <><div className="filters"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search activity" aria-label="Search activity"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter by envelope"><option value="">All envelopes</option>{envelopes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort transactions"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest amount</option><option value="lowest">Lowest amount</option></select></div>{visible.length?<div className="activity-list">{visible.map(row=><article className="transaction-row" key={row.id}><span className={`transaction-icon ${row.envelopeAccent}`}><EnvelopeIcon name={row.envelopeIcon}/></span><div className="transaction-copy"><strong>{row.title}</strong><span>{row.envelopeName} · {new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(new Date(row.transactionDate))}{row.merchant?` · ${row.merchant}`:""}</span></div><strong className={row.type==="saving"?"positive":""}>{row.type==="saving"?"+":"−"}{formatMoney(row.amount)}</strong><div className="row-actions"><button onClick={()=>setEditing(row)} aria-label={`Edit ${row.title}`}><Pencil/></button><button onClick={()=>remove(row.id)} aria-label={`Delete ${row.title}`}><Trash2/></button></div></article>)}</div>:<div className="empty-state compact"><span><ArrowDownLeft/></span><h3>No spending yet</h3><p>Your budget is untouched. Add an expense when money moves.</p></div>}<Dialog open={Boolean(editing)} onClose={()=>setEditing(null)} title="Edit expense" eyebrow={editing?.envelopeName}><form className="form-grid" onSubmit={update}><label><span>Description</span><input name="title" defaultValue={editing?.title} required/></label><label><span>Amount</span><div className="money-input"><b>₹</b><input name="amount" defaultValue={editing?.amount} inputMode="decimal" required/></div></label><label><span>Date</span><input type="date" name="date" defaultValue={editing?new Date(editing.transactionDate).toISOString().slice(0,10):""} required/></label><label><span>Merchant <i>optional</i></span><input name="merchant" defaultValue={editing?.merchant??""}/></label><label><span>Note <i>optional</i></span><textarea name="note" defaultValue={editing?.note??""} rows={2}/></label><button className="primary-button" disabled={pending}>{pending?"Saving…":"Save expense"}</button></form></Dialog></>;
}
