"use client";
import { ArrowRight, Globe2, Eye, EyeOff } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { apiRequest } from "@/lib/api-client";
import { BrandLogo } from "./brand-logo";
export function AuthForm({ mode, oauthError }: { mode: "sign-in" | "sign-up"; oauthError?: string }) {
  const [show, setShow] = useState(false); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const router = useRouter(); const signup = mode === "sign-up";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const data = new FormData(event.currentTarget); try { await apiRequest(`/api/v1/auth/${signup ? "register" : "login"}`, { method: "POST", body: JSON.stringify({ displayName: data.get("displayName"), email: data.get("email"), password: data.get("password"), client: "web" }) }); router.push("/"); router.refresh(); } catch (error) { setError(error instanceof Error ? error.message : "Something went wrong"); } finally { setPending(false); } }
  const oauthMessage=oauthError==="cancelled"?"Google sign-in was cancelled. Please try again when you are ready.":oauthError?"Google sign-in could not be completed. Please try again.":"";
  return <main className="auth-page"><section className="auth-art"><BrandLogo className="auth-brand"/><div className="auth-message"><span className="eyebrow">हर रुपये की सही जगह</span><h1>Money with<br/><em>clear direction.</em></h1><p>Plan with intent, see your progress, and make every rupee feel accounted for.</p></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="coin coin-one">₹</div><div className="coin coin-two">₹</div></section><section className="auth-card"><div className="auth-inner"><BrandLogo className="mobile-auth-logo"/><span className="eyebrow">{signup ? "Begin with clarity" : "Welcome back"}</span><h2>{signup ? "Create your Li-Khata" : "Welcome to Li-Khata"}</h2><p>{signup ? "Your account starts completely clean—just your plans, never demo data." : "Your monthly plan is waiting for you."}</p>{oauthMessage&&<div className="form-error" role="alert">{oauthMessage}</div>}<a className="google-button" href="/api/v1/auth/google"><Globe2/>Continue with Google</a><div className="auth-divider"><span/>or continue with email<span/></div><form className="form-grid auth-form" onSubmit={submit}>{signup && <label><span>Name</span><input name="displayName" autoComplete="name" placeholder="Your name" required minLength={2} /></label>}<label><span>Email</span><input type="email" name="email" autoComplete="email" placeholder="you@example.com" required /></label><label><span>Password</span><div className="password-input"><input type={show ? "text" : "password"} name="password" autoComplete={signup ? "new-password" : "current-password"} placeholder={signup ? "10+ characters" : "Your password"} required minLength={signup ? 10 : 1} /><button type="button" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff /> : <Eye />}</button></div></label>{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button" disabled={pending}>{pending ? "Please wait…" : signup ? "Create account" : "Sign in"}<ArrowRight /></button></form><p className="auth-switch">{signup ? "Already use Li-Khata?" : "New to Li-Khata?"} <Link href={signup ? "/sign-in" : "/sign-up"}>{signup ? "Sign in" : "Create account"}</Link></p></div></section></main>;
}
