"use client";
import { ArrowRight, Eye, EyeOff, WalletCards } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { apiRequest } from "@/lib/api-client";
export function AuthForm({ mode }: { mode: "sign-in" | "sign-up" }) {
  const [show, setShow] = useState(false); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const router = useRouter(); const signup = mode === "sign-up";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const data = new FormData(event.currentTarget); try { await apiRequest(`/api/v1/auth/${signup ? "register" : "login"}`, { method: "POST", body: JSON.stringify({ displayName: data.get("displayName"), email: data.get("email"), password: data.get("password"), client: "web" }) }); router.push("/"); router.refresh(); } catch (error) { setError(error instanceof Error ? error.message : "Something went wrong"); } finally { setPending(false); } }
  return <main className="auth-page"><section className="auth-art"><Link href="/" className="brand"><span className="brand-mark"><WalletCards /></span><span>Envelope</span></Link><div className="auth-message"><span className="eyebrow">Money, made intentional</span><h1>Give every rupee<br/><em>a purpose.</em></h1><p>A calm, visual way to plan the month, understand your spending, and protect what matters.</p></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="coin coin-one">₹</div><div className="coin coin-two">₹</div></section><section className="auth-card"><div className="auth-inner"><span className="mobile-auth-logo"><WalletCards /> Envelope</span><span className="eyebrow">{signup ? "Begin with clarity" : "Welcome back"}</span><h2>{signup ? "Create your account" : "Sign in to Envelope"}</h2><p>{signup ? "Your new account starts completely clean—just your plans, never demo data." : "Your monthly plan is waiting for you."}</p><form className="form-grid auth-form" onSubmit={submit}>{signup && <label><span>Name</span><input name="displayName" autoComplete="name" placeholder="Your name" required minLength={2} /></label>}<label><span>Email</span><input type="email" name="email" autoComplete="email" placeholder="you@example.com" required /></label><label><span>Password</span><div className="password-input"><input type={show ? "text" : "password"} name="password" autoComplete={signup ? "new-password" : "current-password"} placeholder={signup ? "10+ characters" : "Your password"} required minLength={signup ? 10 : 1} /><button type="button" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff /> : <Eye />}</button></div></label>{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button" disabled={pending}>{pending ? "Please wait…" : signup ? "Create account" : "Sign in"}<ArrowRight /></button></form><p className="auth-switch">{signup ? "Already use Envelope?" : "New to Envelope?"} <Link href={signup ? "/sign-in" : "/sign-up"}>{signup ? "Sign in" : "Create account"}</Link></p></div></section></main>;
}
