"use client";
import { useRouter } from "next/navigation";
import { cloneElement, isValidElement, useState } from "react";
import { toast } from "sonner";
import { apiRequest } from "@/lib/api-client";
import type { BudgetSummary } from "./balance-hero";
import { Dialog } from "./dialog";
export function ExpenseDialog({ budget, trigger, defaultEnvelopeId, kind = "expense" }: { budget: BudgetSummary; trigger: React.ReactElement<{ onClick?: () => void }>; defaultEnvelopeId?: string; kind?: "expense" | "saving"; }) {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const router = useRouter();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { await apiRequest("/api/v1/transactions", { method: "POST", body: JSON.stringify({ budgetMonthId: budget.id, envelopeId: data.get("envelopeId"), title: data.get("title"), amount: data.get("amount"), transactionDate: new Date(String(data.get("date"))).toISOString(), merchant: data.get("merchant") || null, note: data.get("note") || null }) }); toast.success(kind === "saving" ? "Saving recorded" : "Expense added"); setOpen(false); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : `Could not add ${kind}`); } finally { setPending(false); } }
  const eligible = budget.envelopes.filter(e => e.type === (kind === "saving" ? "savings" : "expense"));
  return <>{isValidElement(trigger) && cloneElement(trigger, { onClick: () => setOpen(true) })}<Dialog open={open} onClose={() => setOpen(false)} eyebrow={kind === "saving" ? "Grow your reserve" : "Quick entry"} title={kind === "saving" ? "Record a saving" : "Add an expense"}><form className="form-grid" onSubmit={submit}><label><span>Amount</span><div className="money-input"><b>₹</b><input name="amount" inputMode="decimal" placeholder="0" required pattern="\d+(\.\d{1,2})?" autoFocus /></div></label><label><span>Description</span><input name="title" placeholder={kind === "saving" ? "What are you saving for?" : "What did you spend on?"} required maxLength={120} /></label><label><span>Envelope</span><select name="envelopeId" required defaultValue={defaultEnvelopeId ?? ""}><option value="" disabled>Choose an envelope</option>{eligible.map(e => <option key={e.id} value={e.id}>{e.name} · {e.remaining} left</option>)}</select></label><div className="field-row"><label><span>Date</span><input type="date" name="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label><span>{kind === "saving" ? "Source" : "Merchant"} <i>optional</i></span><input name="merchant" placeholder={kind === "saving" ? "Account or source" : "Store or person"} maxLength={120}/></label></div><label><span>Note <i>optional</i></span><textarea name="note" rows={2} placeholder="Add a useful detail" maxLength={500}/></label><button className="primary-button" disabled={pending}>{pending ? "Saving…" : kind === "saving" ? "Record saving" : "Add expense"}</button></form></Dialog></>;
}
