"use client";
import { useRouter } from "next/navigation";
import { cloneElement, isValidElement, useState } from "react";
import { toast } from "sonner";
import { apiRequest } from "@/lib/api-client";
import type { BudgetSummary } from "./balance-hero";
import { Dialog } from "./dialog";
export function ExpenseDialog({ budget, trigger }: { budget: BudgetSummary; trigger: React.ReactElement<{ onClick?: () => void }>; }) {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const router = useRouter();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { await apiRequest("/api/v1/transactions", { method: "POST", body: JSON.stringify({ budgetMonthId: budget.id, envelopeId: data.get("envelopeId"), title: data.get("title"), amount: data.get("amount"), transactionDate: new Date(String(data.get("date"))).toISOString(), merchant: data.get("merchant") || null, note: data.get("note") || null }) }); toast.success("Expense added"); setOpen(false); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not add expense"); } finally { setPending(false); } }
  return <>{isValidElement(trigger) && cloneElement(trigger, { onClick: () => setOpen(true) })}<Dialog open={open} onClose={() => setOpen(false)} eyebrow="Quick entry" title="Add an expense"><form className="form-grid" onSubmit={submit}><label><span>Amount</span><div className="money-input"><b>₹</b><input name="amount" inputMode="decimal" placeholder="0" required pattern="\d+(\.\d{1,2})?" autoFocus /></div></label><label><span>Description</span><input name="title" placeholder="What did you spend on?" required maxLength={120} /></label><label><span>Envelope</span><select name="envelopeId" required defaultValue=""><option value="" disabled>Choose an envelope</option>{budget.envelopes.filter(e => e.type === "expense").map(e => <option key={e.id} value={e.id}>{e.name} · {e.remaining} left</option>)}</select></label><div className="field-row"><label><span>Date</span><input type="date" name="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label><span>Merchant <i>optional</i></span><input name="merchant" placeholder="Store or person" /></label></div><label><span>Note <i>optional</i></span><textarea name="note" rows={2} placeholder="Add a useful detail" /></label><button className="primary-button" disabled={pending}>{pending ? "Saving…" : "Add expense"}</button></form></Dialog></>;
}
